### ISSUE TITLE
Task2 baseline - repeated instances after preprocessing

### ISSUE THREAD

**Issue by zsozso21** [yseop/YseopLab#26]
Hi,

first, thank you for the updates. The baselines and especially the new scoring functions are very useful.

When I started debugging the task2_baseline.py I think I found a bug. There is a huge amount of repeated instances in the _data_ variable, which is the input of the train and test datasets. In the following picture, there are 9 occurrences of the instance which start with: "It found that total U.S. ...".
![baseline_data](https://user-images.githubusercontent.com/5490469/80050426-d6a27580-8515-11ea-9325-53569d4aa020.png)
I found the problem should be in somewhere in _the make_causal_input_ function because the input lodict_ contains 641 instances, but the length of the output (_hometags_) is 205761.

**Comment by dmariko-yseop** [comment]
Hi, 
yes, still a lot of preproc and compute bugs in `task2_baseline.py`, will be updated tonight
